### PR TITLE
Support Sodium 0.5.3 and above

### PR DESCRIPTION
**Pull request by Obydux**

### CODE REVIEW

**Comment by Eveeifyeve** [comment]
I would like to see that this updates to 0.5.6 because indium has issues with my mods because it below the speed of updates.

**Comment by OpenBagTwo** [comment]
I succeeded in building @Obydux's branch, and in a fresh instance I was able to load the game, create a world and load a shader (Complementary 5.1.1 + Euphoria Patches).

<details><summary> Mod and system stack</summary>

- Linux x86_64
- PrismLauncher
- AMD 5900X + AMD 6700XT
- Minecraft 1.20.4
- Fabric Loader 0.15.6
- Sodium 0.5.7
- Lithium 0.12.1
- Iris 1.6.15
- Sound Physics Remastered 1.20.4-1.3.1
- ReplayMod 1.20.4-2.6.14
- EuphoriaPatcher 0.3.0-fabric
</details>

I do have crashes when upgrading one of my existing instances to the Sodium 0.5.7 stack, but that one has far more mods, and I have no reason to expect that the issue is with Indium.

**Comment by SettingDust** [comment]
He does nothing about coding in this PR. You can just use fabric dependencies override with the latest Indium
https://github.com/comp500/Indium/issues/271#issuecomment-1916088926

**Comment by OpenBagTwo** [comment]
> He does nothing about coding in this PR.

Is there any reason to expect that code changes are needed for the new version of Sodium? Specifically referencing:

> I don't recommend this. Some glitches would hurt players with huge mod lists.

_Originally posted by @DroidZed in https://github.com/comp500/Indium/issues/271#issuecomment-1916547531_

are there known / suspected incompatibilities with the latest changes introduced by Sodium?

**Comment by DroidZed** [comment]
> > He does nothing about coding in this PR.
> 
> Is there any reason to expect that code changes are needed for the new version of Sodium? Specifically referencing:
> 
> > I don't recommend this. Some glitches would hurt players with huge mod lists.
> 
> _Originally posted by @DroidZed in https://github.com/comp500/Indium/issues/271#issuecomment-1916547531_
> 
> are there known / suspected incompatibilities with the latest changes introduced by Sodium?
>             
> 
> 

What I meant was that "some glitches" may affect the users of this mod when applying that "fix".

Ignoring the dependencies just to make the warning go away and have the game run knowing it may break or anything is not a viable solution.

**Comment by NotoriousPyro** [comment]
> > > He does nothing about coding in this PR.
> > 
> > 
> > Is there any reason to expect that code changes are needed for the new version of Sodium? Specifically referencing:
> > > I don't recommend this. Some glitches would hurt players with huge mod lists.
> > 
> > 
> > _Originally posted by @DroidZed in [#271 (comment)](https://github.com/comp500/Indium/issues/271#issuecomment-1916547531)_
> > are there known / suspected incompatibilities with the latest changes introduced by Sodium?
> 
> What I meant was that "some glitches" may affect the users of this mod when applying that "fix".
> 
> Ignoring the dependencies just to make the warning go away and have the game run knowing it may break or anything is not a viable solution.

Considering that's all the author of this mod did to make it compatible for 1.20.4, unless you have evidence that something is broken "visually" then we can surmise that it works given the number of people saying so, and people can report bugs if and when they happen...

**Comment by AutonomousCat** [comment]
Heads up, Sodium is on 0.5.8 now

**Pull request closed without merging**
