### PR TITLE
make indium child of sodium

### PR DESCRIPTION
**Pull request by isXander**

### CODE REVIEW

**Comment by comp500** [comment]
Eh I don't really think it should be one... it's an addon to Sodium but not part of Sodium itself, and making it a child will just result in people not being able to find it in the menu.

**Comment by isXander** [comment]
Sodium Extra is also not part of Sodium yet marks it as a child. There are no settings in Indium so it wouldn't be a bad thing hiding it away in sodium, just a bit of cleanup.

If not, maybe mark Indium as a library so it can be filtered away.

**Comment by comp500** [comment]
My main concern is it getting hidden away, then users not realising that it's installed and thinking it's not working, since it has no visible behaviour other than getting FRAPI to work. I still think that child mods are primarily intended for jar-in-jar mods or modules, like Fabric API. Marking it as a library would be reasonable though.

**Comment by isXander** [comment]
searching for it in modmenu when it's a child should still show it

**Comment by comp500** [comment]
Users won't necessarily use the search bar, especially if they only have a few mods.

**Pull request closed without merging**
