### PR TITLE
FREX support

### LINKED ISSUE #97: Implement FREX 6.x
at startup

https://crashy.net/csoaoLA8NK7tcw3Q51GE

https://crashy.net/NqDeiOLhXKhC51sKnYyW?raw

### PR DESCRIPTION
**Pull request by spiralhalo**
This PR makes Indium a FREX addon rather than FRAPI. FRAPI support is implied as FREX contains a compatibility wrapper for FRAPI.

This PR is based on a project called Plumbum, and it is apparent from the commit history. However, all references to Plumbum has been removed from this PR in the latest commit. Please inform me if you found otherwise! Also if a clean PR is preferred, I can do that, at the cost of losing the commit history.

The FREX implementation is largely based on FREX's "base" implementation which is used by Pastel--FREX's integrated reference implementation. The main difference is the render contexts, which is based on what Indium had that contain the main interaction point with Sodium. Additionally, it also retains Indium's AoCalculator for simplicity.

While this PR tries to maintain parity with Pastel in terms of supported features, some implementation are simplified. E.g. Pastel implements item glint and overlay through adjusting the material before quad rendering, but we simply encode different values or target different RenderType output on similar scenarios, bypassing the material. This should have no side effect, as the material adjustment is done during quad emitting (therefore mods shouldn't be able to access them at this point).

Technically, quad features are implemented via base FREX while tessellation features are implemented in the fashion described above, but I couldn't guarantee all possible scenarios. I've tested this implementation with a handful of mods including Exotic block (custom blocks with connected texture and non-cube shapes, proper AO is working), Campanion (contextual rope bridge model), Connectivity, and LambdaBetterGrass. At the very least, I don't think it could possibly support less features than Indium's current state. I don't mind maintaining in the future if issues arise.

With the support of FREX, this PR also added the ability to apply FREX's json material maps! Currently only blocks and items are supported.

Lastly, as FREX's models have no `isVanillaAdapter` interface, we simply render all models using our renderer. The performance impact for this hasn't been measured.

### CODE REVIEW

**Comment by comp500** [comment]
Whoa, that was fast! I'm rather busy at the moment so I won't be able to review this PR yet, but I'm very interested in merging this.

> Also if a clean PR is preferred, I can do that, at the cost of losing the commit history.

For something this big, commit history is rather more important :P

> This should have no side effect, as the material adjustment is done during quad emitting

Is this after `QuadTransform`s?

> Additionally, it also retains Indium's AoCalculator for simplicity.

Presumably Pastel does contain it's own ambient occlusion code, I wonder if it's any better in terms of performance/compatibility?

**Comment by spiralhalo** [comment]
> Is this after QuadTransforms?

Yes. Essentially the material adjustment is done to simplify vertex encoding and it's done way after the quad can be modified by external processes. Especially true in Pastel since it doesn't perform transform in the render context but instead in model's render function (also applies to FRAPI and vanilla wrapped models).

That said while inspecting I found a difference which I've fixed in the last commit.

> Presumably Pastel does contain it's own ambient occlusion code

It does, but the interface isn't directly compatible and require some block pos to packed section pos conversion. I haven't succeeded in that, but I decided it's not worth the effort since we already have an Ao calculator, and because Pastel's has a "bug" with non-vanilla block models (https://github.com/vram-guild/frex/issues/3) which isn't reproduced in Plumbum.

**Comment by FakeMichau** [comment]
[a4fbf34](https://github.com/comp500/Indium/pull/120/commits/a4fbf34e912ffb8dbb1d24b2de06f333f18a0111) breaks iris upon loading a world, don't know why just wanted to point it out

**Comment by AmonRay** [comment]
it works, but greatly degrades performance on i7-2600k (5ghx + gtx 1070) from 80 fps to 30fps. Tested on AOF5 modpack
[indium.log](https://github.com/comp500/Indium/files/8865548/indium.log)
indium
[plumbium.log](https://github.com/comp500/Indium/files/8865550/plumbium.log)
plumbium

**Comment by spiralhalo** [comment]
Thank you for the reviews! I'll look deeper into it when I'm less busy.

> it works, but greatly degrades performance on i7-2600k (5ghx + gtx 1070) from 80 fps to 30fps. Tested on AOF5 modpack

@AmonRay if you open indium properties file `.minecraft/config/indium-renderer.properties` there is a property called `always-tesselate-blocks`. Can you try comparing the fps between when it's `auto` and when it's `true`? (requires restarting MC to change the property)

**Comment by AmonRay** [comment]
I did not compile indium with this PR. I compiled plumbium so the config file was different `.minecraft/config/plumbum-renderer.properties`

auto - 30-35
true - 38-45

still a noticeable difference in performance, but already better :D

**Comment by AmonRay** [comment]
just tried to run from indium-plumbum-merge branch - crash
[crash-2022-06-12_16.08.18-client.txt](https://github.com/comp500/Indium/files/8885882/crash-2022-06-12_16.08.18-client.txt) (without Not Enought Crashes)

tried to run world with Not Enought Crashes - but its spams into logs (looks like conflict with AE2)
[2022-06-12-7.log](https://github.com/comp500/Indium/files/8885912/2022-06-12-7.log)

**Comment by spiralhalo** [comment]
@AmonRay sorry, I meant base indium without this PR.

**Comment by AmonRay** [comment]
> @AmonRay sorry, I meant base indium without this PR.

-5-10fps with always-tesselate-block=true on basic indium (almost no difference)

**Comment by comp500** [comment]
I might put together some sort of benchmark comparing chunk build performance between Pastel/Plumbum, Indigo/Indium and Sodium - would be useful to see if this causes a performance regression/improvement compared with Sodium directly in terms of chunk building, and whether this can be remedied.

@AmonRay I assume these framerates are while moving around or loading chunks? Please test again while standing still once all chunks have loaded (ideally press F3+Esc to pause the game) - the framerates should be identical.

**Comment by AmonRay** [comment]
@comp500 tested with game pause. Quick reminder: it's not a clean fabric, its modpack (based on AOF4), most likely it affects

**indium-1.0.6+mc1.18.2.jar + BSL shaders**
_always-tesselate-block=auto_ 




_always-tesselate-block=true_ 



**plumbum-0.1.0-dev.unknown+mc1.18.2.jar + BSL shaders**
_always-tesselate-block=auto_ 



_always-tesselate-block=true_  + BSL shaders


maybe there is some kind of benchmark mod for fabric loader? I would run tests for all cases
if it helps somehow I can share my modpack

**Pull request closed without merging**
