### PR TITLE
Update to Sodium 0.3.3

### LINKED ISSUE #92: Crash when loading world with the newest version of sodium
Minecraft 1.17.1
Java 16.0.1 64-bit
Sodium version: 0.3.3 build 8
Indium version: 1.0.0
Crash happened when trying to load a world.
Crash log: [crash-2021-11-23_19.04.41-client.txt](https://github.com/comp500/Indium/files/7589840/crash-2021-11-23_19.04.41-client.txt)

I also experienced crashes before updating sodium.

### PR DESCRIPTION
**Pull request by IMS212**
This will not build unless you provide a custom Sodium jar, as 0.3.3 is not released yet.

### CODE REVIEW

**Comment by comp500** [comment]
Thanks! Could you PR against 1.17.x/dev? That should build against the Sodium dev branch directly, if Gradle decides to work.

**Comment by DragonEggBedrockBreaking** [comment]
Sodium 0.3.3 has been released now. @IMS212

**Comment by IMS212** [comment]
1.17.x/dev does not exist, and in any case Sodium 0.3.3 has released.

**Comment by comp500** [comment]
I meant `1.17.x/main`.. I think I can make the change myself anyway.

**Comment by IMS212** [comment]
you'll need to update the buildscript to actually compile 0.3.3 lol

**Pull request merged**
