### PR TITLE
Fixes and optimizations

### LINKED ISSUE #9: Use VertexSinks directly in all rendering code
This means we can get rid of `VertexConsumerSinkShim` and have better performance.

### LINKED ISSUE #64: Sodium with Indium: AOF3 Modern Industrialization machine animation
Mods: AOF3 2.8.4, with "modern-industrialization 0.4.0-alpha.10" (changed from 2.8.4's alpha 8), added with "indium-1.0.01.16.5-a997c55.jar" (AOF3 team's FAQ linked) and "sodium-fabric-mc1.16.5-0.2.0+build.4.jar"

When I enable the setting "Animate Only Visible Textures" in Sodium the blocks with a conditional animated texture (like machines which animate when working) only display a single frame of their animation. Changing the setting instantly let's them continue while enabling it again stops them at the current frame. Blocks with always-on animations like fluid pipes which has the water animation sequence inside them works fine.
Java 16, 8600K, RX 570, Mesa 18.3.6, Debian 10

p.s. Downloaded current code and used the wrapper to compile. Issue persists.

### LINKED ISSUE #83: Textures on meshes aren't animated
If a mesh is consumed by the mesh consumer inside emitBlockQuads, any textures that are normally animated will be locked on their first frame. Toggling Sodium's "Animate Only Visible Textures" option doesn't do anything either. This behavior can be observed through mods like ConnectedTexturesMod For Fabric (CTMF) and JSON Model Extensions (JMX).

### PR DESCRIPTION
**Pull request by PepperCode1**
- Optimize terrain building by using Sodium's ChunkModelBuilder directly; Resolve #9
- Fix compatibility with Sodium's "animate only visible textures" option; Fix #83, fix #64
- Port recent Indigo bug fixes
- Other optimizations
- Rename all occurrences of Indigo to Indium
- Make all indentation use tabs
- Update Gradle and build dependencies
- Update gitignore to support Eclipse

### CODE REVIEW

**Comment by comp500** [comment]
Oooh, this looks very interesting, thank you!

**Comment by comp500** [comment]
Hmm, ideally I'd cache the sprite at some point so it doesn't have to run SpriteFinder every frame (buffer) / chunk build (terrain). The code seems to also pass fallback `BakedQuad`s through that same code, even though they already contain the sprite so it doesn't need to be looked up. From a bit of profiling though it doesn't seem to have much of an impact.

Animations in buffer (non-terrain) quads don't seem to work properly; I don't think this causes a problem with `BakedModel` fallback instances since those will have `SpriteUtil.markSpriteActive` called at some point, but FRAPI Meshes won't do so. The easiest way I've found to observe this is to break a Magma block with a Bits and Chisels chisel to get a Magma Block Bit, then ensure there are no Magma blocks in rendered terrain (might need a low render distance).

**Comment by PepperCode1** [comment]
Only the `TerrainQuadRenderer` uses the `SpriteFinder`. It will only be used during chunk rebuilds. I will check out and try to fix the other two points.
I see what you mean now. I only touched the terrain rendering in this pull request, but didn't notice that the non-terrain block and item rendering has to mark the sprite as active as well. This can be done easily, but I'm not sure how the caching would work. Do you have ideas?
After some thinking, I see that quads on `Mesh`es can have their `Sprite` cached. One way of doing this could be to add a `Sprite[]`, but this would increase the memory footprint of the `Mesh` by a little bit. I suppose this memory trade-off is preferable to searching up the `Sprite` every time, even if the `SpriteFinder` uses an efficient binary search.

**Comment by comp500** [comment]
> Only the `TerrainQuadRenderer` uses the `SpriteFinder`.

I meant that `TerrainFallbackConsumer` is a subclass which has the `BakedQuad` instance... but I just realised that a `QuadTransform` can change sprite atlas coordinates, so it isn't safe to reuse the sprite in that `BakedQuad` anyway.

> ... but I'm not sure how the caching would work. Do you have ideas?

For dynamic quads using `QuadEmitter` directly during rendering, I don't think you'd be able to cache anything; but with `Mesh` you could store a list of `Sprite`s, like `ChunkModelBuilder.addSprite`. In <https://github.com/comp500/Indium/issues/83#issuecomment-899659106> I was thinking you could make it part of the `QuadViewImpl`/`EncodingFormat` vertex format but then you wouldn't be able to use a direct object reference; a single list per `Mesh` is more efficient anyway.

**Comment by PepperCode1** [comment]
The transforms are a good point. The `BakedQuad` sprite or `MeshImpl` `Sprite[]` would only work if no transforms are applied. I think this fact makes doing this not worth it, because maintaining a `Sprite[]` requires tracking all `MeshImpl` instances and updating all sprites on resource reload, since the atlas is recreated.

**Comment by comp500** [comment]
Hmm yeah, I guess you could add a sprite reference (hashmap index? I seem to remember Canvas doing something similar) to the `QuadViewImpl` vertex format instead? Then if the `QuadTransform` changes the texture coordinates the cached sprite reference can be removed/regenerated.

I think on resource reload the renderer is recreated? That should destroy all `MeshImpl` instances on resource reload anyway.

**Comment by PepperCode1** [comment]
Neither the renderer nor the meshes are recreated on resource reload. I don't know how changing the vertex format would help but perhaps retrieving all UV values before and after the transform would work. I think doing this would negate any benefit gained from using the sprite array, which was probably negligible in the first place.

**Comment by comp500** [comment]
> Neither the renderer nor the meshes are recreated on resource reload.

Ah I was wrong there, but meshes from all mods still need to be recreated on resource reload otherwise their textures will break. Most mods will cache `Mesh` instances as part of their block models, which should be recreated on resource reload as they're supplied to the game through `ModelResourceProvider`. So we can rely on having constant `Sprite` references in the same way as the `Mesh` vertex data relies on constant UV coordinates.

> I don't know how changing the vertex format would help but perhaps retrieving all UV values before and after the transform would work.

`MutableQuadView` keeps the vertex `int[]` data opaque to the caller, so you can store the `MeshImpl` `Sprite[]` array index in the vertex format header without affecting any other code, just by adding a field in `EncodingFormat` (the toVanilla code does an array copy, but only looks at data past the header). There's no need to keep track of UV values before/after `QuadTransform`s, just set the cached index to an invalid marker value in `MutableQuadViewImpl.sprite`. Then in `TerrainMeshConsumer.renderQuad`/`BufferMeshConsumer.renderQuad` you can index the array and mark the sprite as active, if there is a cached index (after quad transforms are processed) - so you'd at least be able to cache quads that have `QuadTransform`s that don't modify the texture coordinates.

**Comment by PepperCode1** [comment]
Alright, this should work, however there is one more issue. What happens if a mesh is built before the atlas is created? Should it be classified as undefined behavior that might crash the game?

**Comment by comp500** [comment]
I think so, especially since `spriteBake` would need to use the atlas too.

**Pull request merged**
