### PR TITLE
Update to Sodium 0.5.11

### PR DESCRIPTION
**Pull request by AnttiMK**
Sodium 0.5.11 was recently released, did some quick running around in-game and seems to work fine :)

### CODE REVIEW

**Comment by Fyoncle** [comment]
He already can do it by himself, he doesn't like unofficial builds in there specially for Sodium stuff that only changes the version in the code.
image
Which is clear from the closed pull requests...

**Review by Thinkseal — APPROVED** [review]

**Comment by Jozkah** [comment]
can you post artifacts?

**Comment by drwoops** [comment]
There is actually important fixes in sodium 0.5.11 e.g. so that the hyper realistic sky resource pack doesn't crash. I would really like to see an indium update so that i can use that

**Comment by Jozkah** [comment]
> There is actually important fixes in sodium 0.5.11 e.g. so that the hyper realistic sky resource pack doesn't crash. I would really like to see an indium update so that i can use that

not only that but iris was unusable on 0.5.9 causing crashes after map load, was fixed on .11

**Pull request closed without merging**
