### PR TITLE
Mod icon

### PR DESCRIPTION
**Pull request by TechnicProblem**
I made an icon for the mod, resolving issue #38.

### CODE REVIEW

**Comment by DragonEggBedrockBreaking** [comment]
I believe the icon is normally `assets/modid/icon.png` (in this case `modid` is `indium`)

**Comment by TechnicProblem** [comment]
Thank you, I have now moved the file.

**Comment by comp500** [comment]
Could you resize it to 128x128? As it's only displayed in Mod Menu, it doesn't need to be anywhere near as large as it is.

**Comment by TechnicProblem** [comment]
Yes, have fixed it.

**Comment by comp500** [comment]
Thanks!

**Pull request merged**
